blank_issues_enabled: false
contact_links:
  - name: 🙋 Ask a Question
    url: https://github.com/your-username/your-repo/discussions
    about: Ask questions and discuss ideas in the Discussions tab.
