name: Bug 回報
description: 提交一個錯誤 / 問題
title: "[BUG] 標題"
labels: ["type: bug(fix)"]
body:
- type: checkboxes
  attributes:
    label: 是否已存在相關的問題？(必填)
    description: 請搜尋看看是否已有類似的錯誤問題。
    options:
    - label: 我已搜尋過現有的問題
      required: true
- type: input
  attributes:
    label: 發生時間(必填)
    description: 格式 YYYY-MM-DD HH:MM
  validations:
    required: true
- type: textarea
  attributes:
    label: 當前行為(必填)
    description: 簡單描述做了什麼事情
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: 預期行為
    description: 簡單描述原本預期會發生什麼事情
    render: markdown
  validations:
    required: false
- type: input
  attributes:
    label: 網站版本號
    description: 位於網站下方
  validations:
    required: false
- type: textarea
  attributes:
    label: 平台環境
    description: |
      例:
        - **作業系統**: Ubuntu 20.04
        - **瀏覽器**: Chrome
        - **瀏覽器版本**: 13.14.0
    value: |
        - 作業系統:
        - 瀏覽器:
        - 瀏覽器版本:
    render: markdown
  validations:
    required: false
- type: input
  attributes:
    label: 網站錯誤碼
  validations:
    required: false
- type: textarea
  attributes:
    label: 其他補充
    description: |
      任何連結、截圖或影片等補充訊息，都可以寫在這裡。
      提示：可以點擊此區域以突出顯示，然後拖入圖片或相關文件。
  validations:
    required: false